### ISSUE TITLE
Solr setting location seems give problem

### ISSUE THREAD

**Issue by mccrodp** [mparker17/docker-solr-apachesolr#1]
I am getting the following when I run Docker Compose:

<pre>
HTTP ERROR 500

Problem accessing /solr/. Reason:

    {msg=SolrCore 'collection1' is not available due to init failure: Could not load conf for core collection1: Error loading solr config from /opt/solr/example/solr/collection1/conf/solrconfig.xml
</pre>

I place the apachesolr module from drupal.org in the same directory as the Dockerfile and the settings seem to copy over ok. However, when I ssh into the docker container it seems their is drupal config at both:

``/opt/solr/`` and ``/opt/solr-4.10.4/``

Any ideas on this one?

<pre>
solr@a69ccd61c2fc:/opt/solr/example/solr/collection1/conf$ cat schema.xml | grep drupal
<schema name="drupal-4.1-solr-4.x" version="1.3">
</pre>

**Comment by mparker17** [comment]
I will investigate this... it sounds like Drupal's Apache Solr Search module has updated their schema since I last worked on this image.

In the meantime, you should be able to get this image to build properly by issuing the following commands...

```
$ git clone --recursive https://github.com/mparker17/docker-solr-apachesolr.git
$ cd docker-solr-apachesolr
$ docker build -t solr-apachesolr .
```

***

Background...

I used [Git Submodules](http://git-scm.com/book/en/v2/Git-Tools-Submodules) to ensure that a specific revision of the Apache Solr Search Drupal module is used when adding files to the Docker container.

Git submodules are a little weird because they don't work properly unless you follow a very specific procedure... you either have to `git clone --recursive` from the beginning, or `git submodule init && git submodule update` if you didn't recursively clone. Also, frustratingly, if you fiddle with submodule-related stuff, it tends to break in non-trivial-to-debug-and-fix ways. (generally, I try to avoid submodules in favour of package managers like `composer`, but there are some very specific instances (like this one) when they are the best tool for the job).

While I'm updating the version of the Apache Solr Search module being used, I will also update the README to better explain how to clone / use this repository.

**Comment by mccrodp** [comment]
Again, thanks @mparker17 great info, especially the part on submodules, I actually didn't know about ``--recursive``.

So, yea, the Drupal solr module > Solr compatibility is more complicated than I expected. It is a surprise that there would be a schema update using the same major version of Solr, but perhaps it is an incremental ``4.x`` minor update...I thought they listed the version as ``4.x`` rather than something specific like ``4.10.4``.

Anyways, good to know and I'll just use the submodule version you have included in future, unless a specific drupal solr module version is required and then I'll test with that. Thanks.

**Comment by mparker17** [comment]
@mccrodp I got a chance to update this image to:

* use the Solr configuration in the latest commit to the `apachesolr` module's `7.x-1.x` branch (commit [344c6d7](http://cgit.drupalcode.org/apachesolr/commit/?id=344c6d76eb053f7d2c2d38046243865243412ddf)),
* Use Solr 5 (now that the apachesolr module contains Solr 5-compatible configuration)
* Make it possible to change the name of the Solr core from `collection1` to whatever you want it to be via the `SOLR_CORE_NAME` environment variable.

**Comment by mccrodp** [comment]
That's fantastic, many thanks for this, @mparker17. Will test it out soon.
